#!/bin/bash

# Define variables

PODFILE="Podfile.lock"
DEPENDENCIES="DEPENDENCIES"
IFS=$'\n'       # make newlines the only separator
set -f

# Define functions

function listAll {         
	for i in $(cat "$PODFILE"); do
		if [[ $i == *"DEPENDENCIES"* ]]
			then
				break
			else		
  				echo "$i" | grep "^  -"
  		fi
	done
	exit
}

function listPods {
	readLine=false
	for i in $(cat "$PODFILE"); do
		if [[ $i == *"DEPENDENCIES"* ]]
			then
				readLine=true
			else
				if [[ $readLine == true ]]
					then
  						echo "$i" | grep "^  -"
  				fi	
  		fi
	done
	exit
}

function showInfo {
	echo -e "Usage: \n\t$ llpod "
	echo -e "\n\tCommand to list selected pod.\n"
	echo -e "Options: \n\t--v\t\tShow all pods with all submodules.\n\t--help\t\tShow help."
}

function readParameters {
	for parameter in $@
	do
  		case "$parameter" in
  			"--v") listAll
   			;;
  	 		"--help") showInfo
   			;;
   			*"--"*) echo "Option \""$parameter"\" unrecognized." && exit
			;;
   			*) PODFILE="$parameter"
   			;;
		esac
	done	
}

# Read parameters 

readParameters $@

# Check Podfile

if [ -f "$PODFILE" ]
  	then
    		listPods
	else
		echo "Cannot find any podfile named" "\"""$PODFILE""\""
		exit			
fi
